---
- hosts: all
  become: true
  tasks:
    - name: Installing aptitude using Ubuntu apt package manager
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install dependenciesnpackages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repos
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Python Module
      pip:
        name: docker
